---
# defaults

# Database setup
create_db: yes
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_max_pool_size: 5
module_database: okapi_modules
module_env:
  - { name: db.host, value: "{{ pg_host }}" }
  - { name: db.port, value: "{{ pg_port }}" }
  - { name: db.database, value: "{{ module_database }}" }
  - { name: db.username, value: "{{ pg_admin_user }}" }
  - { name: db.password, value: "{{ pg_admin_password }}" }
  - { name: db.maxPoolSize, value: "{{ pg_max_pool_size }}" }

# If the module_env list is populated, it will set global module environment variables
# These environment variables can be overridden by the docker_env property of the folio_modules entries

# Okapi setup
folio_modules: []
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
tenant: diku
deploy_timeout: 900
