---
mod_auth_home: /opt/mod-auth
mod_auth_src_home: /opt/mod-auth-src
okapi_url: http://localhost:9130/
auth_modules:
  - { index: 0, module: login }
  - { index: 1, module: authtoken }
  - { index: 2, module: permissions }
folio_user: folio
folio_group: folio

