---
# defaults
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
auth_required: no

admin_user: 
  username: diku_admin 
  password: admin 

tenant: diku

update_repo: yes
force_repo_update: yes
module_version: HEAD
working_dir: /tmp/module-sample-data

# Status code for duplicate key
duplicate_key_error: 422

# undefined by default, need to be defined for the role to work
# Module name, e.g. mod-vendors
module_name:
# Git URL for repository, e.g. https://github.com/folio-org/mod-vendors
repository:
# List of files to load per endpoint, e.g. { load_endpoint: /vendor, fileglob: sample-data/vendors/*.json }
# Override duplicate_key_error here with variable dup_override
files: []
