---
# mod-codex-mock-data role
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
auth_required: false
mod_codex_mock_prefix: mod-codex-mock
admin_user: { username: diku_admin, password: admin }
mod_codex_mock_permissions: []
auth_by_username: false
top_down_install: false
