---
# Role to tidy up a Vagrant box for packaging
# Note that vagrant-tidy.sh destroys all free disk space!
- name: Copy vagrant-tidy.sh to /root
  become: yes
  copy: src=vagrant-tidy.sh dest=/root/vagrant-tidy.sh mode=0700

- name: Stop services
  become: yes
  service: name={{ item }} state=stopped
  with_items:
    - okapi-deploy
    - okapi
    - docker
    - postgresql
  ignore_errors: yes

# packer sticks this in here?
- name: Remove guest additions ISO, if there
  become: yes
  command: rm -rf /home/vagrant/VBoxGuestAdditions.iso

- name: Run vagrant-tidy.sh
  become: yes
  command: /root/vagrant-tidy.sh
