---
# Role to enable mod-user-import for the sample tenant

# wait a few seconds to make sure modules are spun up
- wait_for: timeout=10

- set_fact:
    mod_user_import_module: "{{ okapi_modules|selectattr('id','match','^'+mod_user_import_prefix+'(-[0-9].*)?$')|list }}"


- name: Check mod-user-import deployment
  uri:
    url: "{{ okapi_url }}/_/discovery/modules/{{ mod_user_import_module.0.id }}"
    status_code: 200, 404
  register: mod_user_import_deploy
  when: not top_down_install

- name: Set mod-user-import deployment status for top down install
  set_fact:
    mod_user_import_deploy:
      status: 200
  when: mod_user_import_deploy.skipped is defined and mod_user_import_deploy.skipped

- name: Check tenant mod-user-import registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules/{{ mod_user_import_module.0.id }}"
    status_code: 200, 404
  when: mod_user_import_deploy.status == 200
  register: tenant_mod_user_import

- name: Enable mod-user-import module for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules"
    method: POST
    body_format: json
    body: '{ "id" : "{{ mod_user_import_module.0.id }}" }'
    status_code: 201
  register: mod_user_import_enable
  changed_when: mod_user_import_enable.status == 201
  when: mod_user_import_deploy.status == 200 and tenant_mod_user_import.status == 404 and not top_down_install

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: mod_user_import_login
  when: mod_user_import_deploy.status == 200 and auth_required

- name: Assign mod-user-import permissions to other users (auth by username)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ item.0.username }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      X-Okapi-Token: "{{ mod_user_import_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item.1 }}" }'
    status_code: 200,422
  register: mod_user_import_perms
  changed_when: mod_user_import_perms.status == 200
  with_subelements:
    - "{{ mod_user_import_permissions }}"
    - permissions
  when: mod_user_import_deploy.status == 200 and auth_required and auth_by_username

- name: Assign mod-user-import permissions to other users (auth by id)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ item.0.perms_user_id }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      X-Okapi-Token: "{{ mod_user_import_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item.1 }}" }'
    status_code: 200,422
  register: mod_user_import_perms
  changed_when: mod_user_import_perms.status == 200
  with_subelements:
    - "{{ mod_user_import_permissions }}"
    - permissions
  when: mod_user_import_deploy.status == 200 and auth_required and not auth_by_username
