---
- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload

- name: Restart inventory-storage
  become: yes
  service: name=inventory-storage state=restarted

- name: Restart inventory
  become: yes
  service: name=inventory state=restarted

