---

- name: Create tmp directory to locate sample data
  tempfile:
    path: /tmp
    state: directory
  register: tmpdir_sample

- name: Clone repo with sample data
  git: repo={{ repository }} dest={{ tmpdir_sample.path }}/{{ module_name }} version={{ module_version }} update={{ update_repo }} force={{ force_repo_update }}
  vars:
    ansible_become: false
  delegate_to: 127.0.0.1

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

- name: Load module data
  include: load-data.yml load_endpoint={{ item.load_endpoint }} fileglob={{ item.fileglob }} dup_key={{ item.dup_override|default(duplicate_key_error) }} http_method={{ item.http_method|default('POST') }} updated_code={{ item.updated_code|default(201) }} token={{ tenant_admin_login.x_okapi_token|default('token') }}
  with_items: "{{ files }}"

- name: Remove tmp sample data dir
  command: rm -rf {{ tmpdir_sample.path|quote }}
  args:
    removes: "{{ tmpdir_sample.path }}"
