---
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
folio_user: folio
folio_conf: /etc/folio
tenant: diku
docker_repo: folioci  
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
module_database: okapi_modules
# pinned modules example
# pinned_modules:
#   - { module: mod-permissions, version: 5.0.1-SNAPSHOT.11 }
pinned_modules: []
# default dockerCMD values for modules
docker_cmd: {}
# default env values for modules
env_var: {}
# default Docker port for modules
docker_port: {}
default_docker_port: 8081
# Other modules to enable outside of dependency resolution
other_mods: []
install_timeout: 300

use_folio_snapshot: false
folio_snapshot_url: 'http://folio-snapshot-stable.aws.indexdata.com'
