---
# wait a few seconds to make sure modules are deployed
- wait_for: timeout=30
  listen: Install modules

- name: Write out install.json file to config directory
  become: yes
  copy: dest={{ folio_conf }}/install.json content={{ module_list|to_nice_json }}
  listen: Install modules

- name: Perform module installation
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ tenant }}/install"
    method: POST
    body_format: json
    body: "{{ module_list }}"
    timeout: "{{ install_timeout }}"
  register: module_install
  changed_when: module_install.status == 200
  listen: Install modules
  
