---

# These tasks require stripes-build with option 'build_install_files' set to 'true'

- name: create temp directory for install files
  tempfile:
    state: directory
    path: /tmp
  register: tempdir_installfiles

- name: fetch enable_file from stripes-build
  fetch:
    flat: yes
    src: "{{ stripes_conf_dir }}/stripes-install.json"
    dest: "{{ tempdir_installfiles.path }}/stripes-install.json" 

- name: set enable_file
  set_fact: enable_file="{{ tempdir_installfiles.path }}/stripes-install.json"

- name: fetch deploy_file from stripes-build
  fetch: 
    flat: yes
    src: "{{ stripes_conf_dir }}/okapi-install.json"
    dest: "{{ tempdir_installfiles.path }}/okapi-install.json"
 
- name: set deploy_file 
  set_fact: deploy_file="{{ tempdir_installfiles.path }}/okapi-install.json"
    
