---
# Role to pull the Docker image from folioci and deploy into running Okapi

#########
# Setup #
#########

- name: Pull the mod-loan-storage Docker image
  become: yes
  become_user: "{{ folio_user }}"
  docker_image: name=folioci/mod-loan-storage tag={{ mod_loan_storage_version }}
  register: mod_loan_storage_pull

- name: Set up mod-loan-storage home directory
  become: yes
  file: state=directory path={{ mod_loan_storage_home }}/bin

- name: Set up mod-loan-storage conf directory
  become: yes
  file: state=directory path={{ mod_loan_storage_conf }}

- name: Copy module descriptor
  become: yes
  get_url: url={{ mod_loan_storage_mod_descriptor }} dest={{ mod_loan_storage_conf }}/ModuleDescriptor.json
  register: mod_loan_storage_mod_descr_update

- name: Copy deployment descriptor
  become: yes
  template: src=DeploymentDescriptor.json.j2 dest={{ mod_loan_storage_conf }}/DeploymentDescriptor.json
  notify:
    - Restart mod-loan-storage

- name: Create mod_loan_storage postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_password }}"
    role_attr_flags: SUPERUSER

- name: Create mod_loan_storage db
  become: yes
  become_user: postgres
  postgresql_db: name={{ mod_loan_storage_db }} owner={{ pg_user }}

- name: Copy mod-loan-storage.conf
  become: yes
  template: src=mod-loan-storage.conf.j2 dest={{ mod_loan_storage_conf }}/mod-loan-storage.conf
  notify:
    - Restart mod-loan-storage

- name: Copy mod-loan-storage.env
  become: yes
  copy: src=mod-loan-storage.env dest=/etc/default/mod-loan-storage
  notify:
    - Restart mod-loan-storage

- name: Copy mod-loan-storage.sh
  become: yes
  copy: src=mod-loan-storage.sh dest={{ mod_loan_storage_home }}/bin/mod-loan-storage.sh mode=0755
  notify:
    - Restart mod-loan-storage

- name: Copy mod-loan-storage.service file
  become: yes
  template: src=mod-loan-storage.service.j2 dest=/etc/systemd/system/mod-loan-storage.service
  register: mod_loan_storage_service_update
  notify:
    - Restart mod-loan-storage

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload
  when: mod_loan_storage_service_update.changed

- name: Enable mod-loan-storage service
  become: yes
  service: name=mod-loan-storage enabled=yes

#########################
# Undeploy if new image #
#########################

- name: Get tenants
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants"
    status_code: 200
  when:
    - mod_loan_storage_pull.changed or mod_loan_storage_mod_descr_update.changed
  register: tenants

- name: Check tenant mod-user registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item.id }}/modules/loan-storage"
    status_code: 200, 404
  when:
    - mod_loan_storage_pull.changed or mod_loan_storage_mod_descr_update.changed
  with_items: "{{ tenants.json | default([]) }}"
  register: tenant_mod_loan_storage

- name: Unregister mod-loan-storage module for tenants if image updated
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item[0].id }}/modules/loan-storage"
    method: DELETE
    status_code: 204
  when:
    - mod_loan_storage_pull.changed or mod_loan_storage_mod_descr_update.changed
    - item[1].status == 200
  with_nested:
    - "{{ tenants.json | default([]) }}"
    - "{{ tenant_mod_loan_storage.results | default([]) }}"

- name: Stop mod-loan-storage service if image updated
  become: yes
  service: name=mod-loan-storage state=stopped
  when:
    - mod_loan_storage_pull.changed or mod_loan_storage_mod_descr_update.changed

- name: Un-register mod-loan-storage if image updated
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/loan-storage"
    method: DELETE
    status_code: 204, 404
  when: mod_loan_storage_pull.changed or mod_loan_storage_mod_descr_update.changed
  register: mod_loan_storage_unreg
  changed_when: "mod_loan_storage_unreg.status == 204"

########################################
# Register and launch mod-loan-storage #
########################################

- name: Check mod-loan-storage module registration
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/loan-storage"
    status_code: 200, 404
  register: mod_loan_storage_reg_status

- name: Register mod-loan-storage module
  shell: "curl -X POST -H \"Content-Type: application/json\" -d @{{ mod_loan_storage_conf }}/ModuleDescriptor.json -sSf {{ okapi_url }}/_/proxy/modules"
  when: mod_loan_storage_reg_status.status == 404
  notify: Restart mod-loan-storage

- meta: flush_handlers
