---
folio_user: folio
mod_metadata_home: /usr/share/folio/mod-metadata
mod_metadata_conf: /etc/folio/mod-metadata
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_user: "{{ pg_admin_user }}"
pg_password: "{{ pg_admin_password }}"
mod_metadata_db: mod_metadata
mod_metadata_modules:
  - { index: 0, module: inventory-storage, mod_descriptor: "https://raw.githubusercontent.com/folio-org/mod-metadata/master/inventory-storage/ModuleDescriptor.json", docker_image: folioci/mod-inventory-storage }
  - { index: 1, module: inventory, mod_descriptor: "https://raw.githubusercontent.com/folio-org/mod-metadata/master/inventory/ModuleDescriptor.json", docker_image: folioci/mod-inventory }
  
