---
# Role to load MODS data into mod-inventory
- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

- name: create temp dir for MODS data
  tempfile: 
    path: /tmp
    state: directory
  register: tmpdir_samplemods

- name: Copy sample MODS data
  copy: 
    src: multiple-mods-records.xml 
    dest: "{{ tmpdir_samplemods.path }}/mod-metadata-mods_ansible.xml"
  register: mods_sample

- name: Copy larger MODS sample
  copy: 
    src: many_mods.xml 
    dest: "{{ tmpdir_samplemods.path }}/mod-metadata-mods-large_ansible.xml"
  register: mods_larger
  when: load_mods_larger

- name: Load sample data from MODS ingest
  command: "/usr/bin/curl -X POST -H 'Content-type: multipart/form-data' -H 'X-Okapi-Tenant: {{ tenant }}' -H 'X-Okapi-Token: {{ tenant_admin_login.x_okapi_token | default('token') }}' -F upload=@{{ tmpdir_samplemods.path }}/mod-metadata-mods_ansible.xml {{ okapi_url }}/inventory/ingest/mods"
  when: mods_sample.changed

- name: Load larger sample data from MODS ingest
  command: "/usr/bin/curl -w '\n' -D - -X POST -H 'Content-type: multipart/form-data' -H 'X-Okapi-Tenant: {{ tenant }}' -H 'X-Okapi-Token: {{ tenant_admin_login.x_okapi_token | default('token') }}' -F upload=@{{ tmpdir_samplemods.path }}/mod-metadata-mods-large_ansible.xml {{ okapi_url }}/inventory/ingest/mods"
  when: load_mods_larger and mods_larger.changed
  register: mods_load
  notify: "Wait for MODS"

- name: Get location for upload status
  set_fact:
    upload_status_location: "{{ mods_load.stdout_lines|default([])|select('match','^Location:')|list|first|default([])|regex_replace('^Location: ') }}"
  when: load_mods_larger

- name: remove sample MODS temp dir
  command: rm -rf {{ tmpdir_samplemods.path|quote }}
  args:
    removes: "{{ tmpdir_samplemods.path }}"

- meta: flush_handlers
