---
# Role to build and deploy FOLIO ui-users

- name: Update stripes-core package.json for ui-users
  become: yes
  become_user: "{{ stripes_user }}"
  lineinfile:
    dest: "{{ stripes_conf }}/package.json"
    line: '    "@folio/users": "^0.0.1-test",'
    insertafter: 'dependencies'
  notify: Restart stripes

- name: Add ui-users to stripes config
  become: yes
  lineinfile:
    dest: "{{ stripes_conf }}/stripes.config.js"
    line: "    '@folio/users': {},"
    insertafter: "modules\\:"
  notify: Restart stripes

- name: Rebuild stripes with ui-users dependency
  become: yes
  become_user: "{{ stripes_user }}"
  command: yarn install
  args:
    chdir: "{{ stripes_home }}"
    creates: "{{ stripes_home }}/node_modules/@folio/users"
  notify: Restart stripes

