---
# role to set up stripes-core from npm repo

- name: create stripes group
  become: yes
  group: name={{ stripes_group }} system=yes

- name: create stripes user
  become: yes
  user: name={{ stripes_user }} system=yes group={{ stripes_group }}

- name: Create stripes directories
  become: yes
  file: path={{ item }} state=directory owner={{ stripes_user }} group={{ stripes_group }}
  with_items:
    - "{{ stripes_home }}"
    - "{{ stripes_conf }}"
 
- name: Move to Node.js 6.X lts
  become: yes
  shell: n lts && touch {{ stripes_conf }}/.set_nodedefault_ansible
  args:
    creates: "{{ stripes_conf }}/.set_nodedefault_ansible"

- name: Configure @folio:registry for stripes-core
  become: yes
  become_user: "{{ stripes_user }}"
  shell: yarn config set @folio:registry {{ folio_registry }} && touch {{ stripes_conf }}/.set_folioregistry_ansible
  args:
    creates: "{{ stripes_conf }}/.set_folioregistry_ansible"
 
- name: Configure @folio-sample-modules:registry for stripes-core
  become: yes
  become_user: "{{ stripes_user }}"
  shell: yarn config set @folio-sample-modules:registry {{ folio_sample_modules_registry }} && touch {{ stripes_conf }}/.set_foliosamplemodulesregistry_ansible
  args:
    creates: "{{ stripes_conf }}/.set_foliosamplemodulesregistry_ansible"

- name: Copy stripes.config.js
  become: yes
  become_user: "{{ stripes_user }}"
  template: src=stripes.config.js.j2 dest={{ stripes_conf }}/stripes.config.js force=no
  notify: Restart stripes

- name: Link stripes.config.js
  become: yes
  become_user: "{{ stripes_user }}"
  file: src={{ stripes_conf }}/stripes.config.js dest={{ stripes_home }}/stripes.config.js state=link
  notify: Restart stripes

- name: Copy package.json
  become: yes
  become_user: "{{ stripes_user }}"
  copy: src=package.json dest={{ stripes_conf }}/package.json force=no
  notify: Restart stripes

- name: Link package.json
  become: yes
  become_user: "{{ stripes_user }}"
  file: src={{ stripes_conf }}/package.json dest={{ stripes_home }}/package.json state=link
  notify: Restart stripes

- name: Install packages for stripes-core
  become: yes
  become_user: "{{ stripes_user }}"
  command: yarn install
  args:
    chdir: "{{ stripes_home }}"
    creates: "{{ stripes_home }}/yarn.lock"
  notify: Restart stripes

- name: Copy stripes.service file
  become: yes
  template: src=stripes.service.j2 dest=/etc/systemd/system/stripes.service
  notify:
    - systemctl daemon-reload
    - Restart stripes

- name: Register stripes with systemd
  become: yes
  service: name=stripes enabled=yes

- name: Check stripes service status
  become: yes
  command: systemctl status stripes
  ignore_errors: yes
  changed_when: no
  register: stripes_status

- name: Notify handler if stripes is down
  debug: msg="Setting stripes to restart"
  when: stripes_status | failed
  changed_when: yes
  notify: Restart stripes

- meta: flush_handlers
