---
# mod-loan-storage role
# folio_user needs to be a user with access to Docker
folio_user: folio
mod_loan_storage_home: /usr/share/folio/mod-loan-storage
mod_loan_storage_conf: /etc/folio/mod-loan-storage
mod_loan_storage_mod_descriptor: https://raw.githubusercontent.com/folio-org/mod-loan-storage/master/ModuleDescriptor.json
mod_loan_storage_version: latest
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_user: "{{ pg_admin_user }}"
pg_password: "{{ pg_admin_password }}"
mod_loan_storage_db: mod_loan_storage
# {{ pg_admin_user }} and {{ pg_admin_password }} from postgresql dependency
