---
# Role to enable modules for a tenant.  Typically only needed 
# when not running a "top down install"

# wait a few seconds to make sure modules are spun up
- wait_for: timeout=30

- debug: var=folio_modules

- debug: var=okapi_modules

- set_fact:
    tenant_modules: "{{ tenant_modules | default([]) + [ okapi_modules|select('match','^' + item.module_id|default(item.name) + '(-[0-9].*)?$')|first ] }}"
  with_items: "{{ folio_modules }}"

- name: Check tenant module registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ tenant }}/modules/{{ item }}"
    status_code: 200, 404
  register: tenant_module_check
  with_items: "{{ tenant_modules }}"

- name: Enable module for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ tenant }}/modules"
    method: POST
    body_format: json
    body: '{ "id" : "{{ item.item }}" }'
    status_code: 201
  register: tenant_module_enable
  changed_when: tenant_module_enable.status == 201
  when: item.status == 404 and not top_down_install
  with_items: "{{ tenant_module_check.results }}"

